#!/usr/bin/env python
# -*- python -*-

import argparse
import importlib
import os.path
import sys

import builtins
import node
import builtin_rules
import utils

bfgfile = 'build.bfg'

parser = argparse.ArgumentParser()
parser.add_argument('builddir', help='build directory')
parser.add_argument('--backend', help='backend', default='make')
args = parser.parse_args()

backend = importlib.import_module('backends.{}'.format(args.backend))
builddir = os.path.abspath(args.builddir)

execfile(os.path.join(builddir, bfgfile), builtins.all_builtins)
backend.write(builddir, node.all_targets)
