#!/usr/bin/env python
# -*- python -*-

import argparse
import importlib
import os.path
import sys

import builtins
import builtin_rules
import utils
from build_inputs import BuildInputs
from environment import Environment

bfgfile = 'build.bfg'

parser = argparse.ArgumentParser()
parser.add_argument('builddir', help='build directory')
parser.add_argument('--backend', help='backend', default='make')
parser.add_argument('--prefix', help='installation prefix', default='/usr')
args = parser.parse_args()

backend = importlib.import_module('backends.{}'.format(args.backend))
env = Environment(srcdir=os.getcwd(), builddir=os.path.abspath(args.builddir),
                  install_prefix=os.path.abspath(args.prefix))

build = BuildInputs()
execfile(bfgfile, builtins.bind(build))
backend.write(env, build)
